# Generated by Django 5.0 on 2023-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('H', 'Head'), ('T', 'Teacher'), ('S', 'Student')], default='S', max_length=9),
        ),
    ]
