# Generated by Django 5.0 on 2023-12-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_time',
        ),
    ]
