# Generated by Django 5.0 on 2023-12-25 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_exam_exam_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('session', models.IntegerField()),
                ('academic_year', models.CharField(max_length=10)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
