# Generated by Django 5.0 on 2023-12-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_exam_exam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_date',
            field=models.DateField(auto_now=True),
        ),
    ]
