# Generated by Django 5.0 on 2023-12-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
    ]
