# Generated by Django 5.0 on 2023-12-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_notice_notice_date'),
        ('academic', '0004_remove_class_duration_remove_class_subject'),
    ]

    operations = [
    ]
