# Generated by Django 5.2.17 on 2026-10-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_merge_20231226_1124'),
        ('academic', '0005_merge_20240706_1507'),
    ]

    operations = [
    ]
